### PR TITLE
ARUHA-713 Don't use random partition strategy in examples

### PR DESCRIPTION
**Pull request by lmontrieux**
[ARUHA 713
](https://techjira.zalando.net/browse/ARUHA-713)
At the moment it isn't possible to change an event type's partition strategy. We should consider allowing it.
allow the move from random
also please update the documentation so the examples do not promote random partitioning

### CODE REVIEW

**Comment by rcillo** [comment]
@lmontrieux maybe it would be good to say some words on the lines of: hash strategy is recommended so that, in the case of duplicated events, both events are guaranteed to go to the same partition.

This is useful for clients deduplicating events.

**Comment by rcillo** [comment]
👍

**Comment by rcillo** [comment]
👍

**Comment by lmontrieux** [comment]
👍

**Pull request merged**
