### PR TITLE
Aruha 933 Document per-ET authorization

### PR DESCRIPTION
**Pull request by lmontrieux**
Documentation for per-ET authorization: creating and deleting event types with an authorization section

### CODE REVIEW

**Comment by lmontrieux** [comment]
@rcillo I've added a warning in bold

**Comment by rcillo** [comment]
👍

**Comment by lmontrieux** [comment]
:+1:

**Comment by lmontrieux** [comment]
👍

**Comment by zrobgar** [comment]
👍

**Comment by zrobgar** [comment]
👍

**Comment by v-stepanov** [comment]
👍

**Pull request merged**
