### PR TITLE
Change the token URL

### PR DESCRIPTION
**Pull request by akauppi**
Fabian Wollert on HipChat #nakadi-users:

> this is indeed wrong, it should be now ...

### CODE REVIEW

**Comment by dehora** [comment]
tagging for https://github.com/zalando/nakadi-manual/issues/14

**Comment by dehora** [comment]
@akauppi can you and @drummerwolli confirm you are confident having an actual Zalando auth token endpoint in public documentation. It's simple enough to mark this as an example url.

**Comment by drummerwolli** [comment]
sry, i was wrong and did not look intensively enough ... i thought there was the real zalando endpoint marked in this documentation, but it is right. i'm for keeping it as it is and not approving this ... my apologies for any confusion that has caused ...

**Comment by akauppi** [comment]
I'm fine having this turned down. Just trying to make sense of nakadi and tokens...

**Pull request closed without merging**
